# Generated by Django 5.1.5 on 2025-07-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='diff_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
